package cafemain;

import dao.DaoImpl;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.AdvancedSearch;
import model.CafeTable;
import model.Item;
import model.Paid;
import model.Product;

public class CalcFrame extends javax.swing.JFrame {

    private DaoImpl dao;
    private float price = 0;

    public CalcFrame() {
        initComponents();
    }

    CalcFrame(DaoImpl dao) {
        try {
            initComponents();
            this.dao = dao;
            List<Paid> paidList = dao.getPaidList();
            ViewPaidListInTable(paidList);
            List<CafeTable> masaList = dao.getCafeTableList();
            ViewMasaInCombo(masaList);
            List<Product> productList = dao.getProductList();
            ViewProductListInTable(productList);
        } catch (Exception ex) {
            Logger.getLogger(CalcFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        bg = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        seperator = new javax.swing.JPanel();
        masaBtn = new javax.swing.JPanel();
        tableIcon = new javax.swing.JLabel();
        tableText = new javax.swing.JLabel();
        menuBtn = new javax.swing.JPanel();
        menuIcon = new javax.swing.JLabel();
        menuText = new javax.swing.JLabel();
        orderBtn = new javax.swing.JPanel();
        orderIcon = new javax.swing.JLabel();
        orderText = new javax.swing.JLabel();
        calcBtn = new javax.swing.JPanel();
        calcIcon = new javax.swing.JLabel();
        calcText = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitIcon = new javax.swing.JLabel();
        loginBtn = new javax.swing.JPanel();
        loginIcon = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        calcTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        beginDate = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gainTxt = new javax.swing.JTextField();
        addProduct = new javax.swing.JButton();
        searchProduct = new javax.swing.JButton();
        searchProductTxt = new javax.swing.JTextField();
        updateProduct = new javax.swing.JButton();
        deleteProduct = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        endDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        minSay = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        maxSay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        beginPrice = new javax.swing.JTextField();
        endPrice = new javax.swing.JTextField();
        searchAdvancedProduct = new javax.swing.JButton();
        searchAdvancedPaid = new javax.swing.JButton();
        masaCombo = new javax.swing.JComboBox();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(java.awt.Color.red);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(54, 33, 89));

        logo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setText("KeepEating");
        logo.setToolTipText("");

        seperator.setBackground(new java.awt.Color(255, 255, 255));
        seperator.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        seperator.setInheritsPopupMenu(true);

        javax.swing.GroupLayout seperatorLayout = new javax.swing.GroupLayout(seperator);
        seperator.setLayout(seperatorLayout);
        seperatorLayout.setHorizontalGroup(
            seperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        seperatorLayout.setVerticalGroup(
            seperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        masaBtn.setBackground(new java.awt.Color(54, 33, 89));
        masaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masaBtnMousePressed(evt);
            }
        });

        tableIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Restaurant Table_45px.png")); // NOI18N

        tableText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tableText.setForeground(new java.awt.Color(255, 255, 255));
        tableText.setText("MASALAR");

        javax.swing.GroupLayout masaBtnLayout = new javax.swing.GroupLayout(masaBtn);
        masaBtn.setLayout(masaBtnLayout);
        masaBtnLayout.setHorizontalGroup(
            masaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masaBtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tableIcon)
                .addGap(18, 18, 18)
                .addComponent(tableText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        masaBtnLayout.setVerticalGroup(
            masaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masaBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );

        menuBtn.setBackground(new java.awt.Color(54, 33, 89));
        menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuBtnMousePressed(evt);
            }
        });

        menuIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Restaurant Menu_45px.png")); // NOI18N

        menuText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        menuText.setForeground(new java.awt.Color(255, 255, 255));
        menuText.setText("MENYU");

        javax.swing.GroupLayout menuBtnLayout = new javax.swing.GroupLayout(menuBtn);
        menuBtn.setLayout(menuBtnLayout);
        menuBtnLayout.setHorizontalGroup(
            menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(menuIcon)
                .addGap(18, 18, 18)
                .addComponent(menuText, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBtnLayout.setVerticalGroup(
            menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnLayout.createSequentialGroup()
                .addGroup(menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        orderBtn.setBackground(new java.awt.Color(54, 33, 89));
        orderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orderBtnMousePressed(evt);
            }
        });

        orderIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Order History_45px.png")); // NOI18N

        orderText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orderText.setForeground(new java.awt.Color(255, 255, 255));
        orderText.setText("SİFARİŞ");

        javax.swing.GroupLayout orderBtnLayout = new javax.swing.GroupLayout(orderBtn);
        orderBtn.setLayout(orderBtnLayout);
        orderBtnLayout.setHorizontalGroup(
            orderBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderBtnLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(orderIcon)
                .addGap(18, 18, 18)
                .addComponent(orderText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderBtnLayout.setVerticalGroup(
            orderBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addComponent(orderText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        calcBtn.setBackground(new java.awt.Color(85, 65, 118));
        calcBtn.setPreferredSize(new java.awt.Dimension(176, 67));
        calcBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                calcBtnMousePressed(evt);
            }
        });

        calcIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Calculator_45px.png")); // NOI18N

        calcText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        calcText.setForeground(new java.awt.Color(255, 255, 255));
        calcText.setText("HESABAT");

        javax.swing.GroupLayout calcBtnLayout = new javax.swing.GroupLayout(calcBtn);
        calcBtn.setLayout(calcBtnLayout);
        calcBtnLayout.setHorizontalGroup(
            calcBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcBtnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(calcIcon)
                .addGap(18, 18, 18)
                .addComponent(calcText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calcBtnLayout.setVerticalGroup(
            calcBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calcIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addComponent(calcText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        exitBtn.setBackground(new java.awt.Color(85, 65, 118));
        exitBtn.setPreferredSize(new java.awt.Dimension(122, 56));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitBtnMousePressed(evt);
            }
        });

        exitIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Exit_45pxNew.png")); // NOI18N

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(exitIcon)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(exitIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        loginBtn.setBackground(new java.awt.Color(85, 65, 118));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtnMousePressed(evt);
            }
        });

        loginIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Person_45px.png")); // NOI18N

        javax.swing.GroupLayout loginBtnLayout = new javax.swing.GroupLayout(loginBtn);
        loginBtn.setLayout(loginBtnLayout);
        loginBtnLayout.setHorizontalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBtnLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(loginIcon)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        loginBtnLayout.setVerticalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(calcBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(masaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bg.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 660));

        content.setBackground(new java.awt.Color(255, 255, 255));

        calcTable.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        calcTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        calcTable.setFocusable(false);
        calcTable.setRowHeight(22);
        calcTable.setSelectionBackground(new java.awt.Color(54, 33, 89));
        jScrollPane1.setViewportView(calcTable);

        productTable.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productTable.setFocusable(false);
        productTable.setRowHeight(22);
        productTable.setSelectionBackground(new java.awt.Color(54, 33, 89));
        jScrollPane2.setViewportView(productTable);

        beginDate.setBackground(new java.awt.Color(255, 255, 255));
        beginDate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("BAŞLANĞIC TARİX");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("QAZANC");

        gainTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        addProduct.setBackground(new java.awt.Color(54, 33, 89));
        addProduct.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        addProduct.setForeground(new java.awt.Color(255, 255, 255));
        addProduct.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Add New_35px.png")); // NOI18N
        addProduct.setText("Əlavə et");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        searchProduct.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Search_30px.png")); // NOI18N
        searchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductActionPerformed(evt);
            }
        });

        searchProductTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchProductTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductTxtActionPerformed(evt);
            }
        });
        searchProductTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchProductTxtKeyReleased(evt);
            }
        });

        updateProduct.setBackground(new java.awt.Color(54, 33, 89));
        updateProduct.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        updateProduct.setForeground(new java.awt.Color(255, 255, 255));
        updateProduct.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Update_35pxÜhite.png")); // NOI18N
        updateProduct.setText("Dəyişdir");
        updateProduct.setMaximumSize(new java.awt.Dimension(133, 43));
        updateProduct.setMinimumSize(new java.awt.Dimension(133, 43));
        updateProduct.setPreferredSize(new java.awt.Dimension(133, 43));
        updateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductActionPerformed(evt);
            }
        });

        deleteProduct.setBackground(new java.awt.Color(54, 33, 89));
        deleteProduct.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        deleteProduct.setForeground(new java.awt.Color(255, 255, 255));
        deleteProduct.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Delete_35pxÜhite.png")); // NOI18N
        deleteProduct.setText("Sil");
        deleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("SON  TARİX");

        endDate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("MİN SAY");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("MAX SAY");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("BAŞLANĞIC QİYMƏT");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("SON QİYMƏT");

        searchAdvancedProduct.setBackground(new java.awt.Color(54, 33, 89));
        searchAdvancedProduct.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        searchAdvancedProduct.setForeground(new java.awt.Color(255, 255, 255));
        searchAdvancedProduct.setText("AXTAR");
        searchAdvancedProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAdvancedProductActionPerformed(evt);
            }
        });

        searchAdvancedPaid.setBackground(new java.awt.Color(54, 33, 89));
        searchAdvancedPaid.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        searchAdvancedPaid.setForeground(new java.awt.Color(255, 255, 255));
        searchAdvancedPaid.setText("AXTAR");
        searchAdvancedPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAdvancedPaidActionPerformed(evt);
            }
        });

        masaCombo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(gainTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(beginDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(endDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(0, 208, Short.MAX_VALUE)))
                                        .addGap(34, 34, 34))))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(searchAdvancedPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(masaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25))))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(addProduct)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(updateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(contentLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(contentLayout.createSequentialGroup()
                                                .addComponent(searchProductTxt)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(searchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(beginPrice)
                                                    .addComponent(minSay))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel7)
                                                    .addComponent(endPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                                    .addComponent(maxSay))))
                                        .addGap(15, 15, 15)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(searchAdvancedProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(masaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(beginDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gainTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchAdvancedPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchProductTxt))
                        .addGap(18, 18, 18)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addProduct))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minSay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxSay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beginPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchAdvancedProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1030, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void masaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaBtnMousePressed
        setColor(masaBtn);
        resetColor(menuBtn);
        resetColor(orderBtn);
        resetColor(calcBtn);
        MainFrame mainFrame = new MainFrame(dao);
        mainFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_masaBtnMousePressed

    private void menuBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnMousePressed
        setColor(menuBtn);
        resetColor(masaBtn);
        resetColor(orderBtn);
        resetColor(calcBtn);
        MenuFrame menuFrame = new MenuFrame(dao);
        menuFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBtnMousePressed

    private void orderBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderBtnMousePressed
        setColor(orderBtn);
        resetColor(menuBtn);
        resetColor(masaBtn);
        resetColor(calcBtn);
        OrderFrame frame = new OrderFrame(dao);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orderBtnMousePressed

    private void calcBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcBtnMousePressed
        setColor(calcBtn);
        resetColor(menuBtn);
        resetColor(orderBtn);
        resetColor(masaBtn);
    }//GEN-LAST:event_calcBtnMousePressed

    private void searchProductTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductTxtActionPerformed

    }//GEN-LAST:event_searchProductTxtActionPerformed

    private void exitBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitBtnMousePressed

    private void loginBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMousePressed
        LoginFrame frame = new LoginFrame(dao);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginBtnMousePressed

    private void searchAdvancedPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAdvancedPaidActionPerformed
        try {
            price = 0;

            AdvancedSearch advancedSearch = new AdvancedSearch();
            if (masaCombo.getSelectedItem() != "") {
                Item masaItem = (Item) masaCombo.getSelectedItem();
                CafeTable cafeTable = new CafeTable();
                cafeTable.setId(masaItem.getId());
                advancedSearch.setCafeTable(cafeTable);

            }

            if (beginDate.getDate() != null) {
                Date beginDateTxt = beginDate.getDate();
                advancedSearch.setBeginDate(beginDateTxt);
            }
            if (endDate.getDate() != null) {
                Date endDateTxt = endDate.getDate();
                advancedSearch.setEndDate(endDateTxt);
            }

            List<Paid> paidList1 = dao.advancedSearch(advancedSearch);
            ViewPaidListInTable(paidList1);
            for (Paid paid : paidList1) {
                price += paid.getPrice();
            }

            if (paidList1 != null) {
                gainTxt.setText(String.valueOf(price));
            }
        } catch (Exception ex) {
            Logger.getLogger(CalcFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchAdvancedPaidActionPerformed

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        AddProduct addProduct = new AddProduct(dao);
        addProduct.setVisible(true);
    }//GEN-LAST:event_addProductActionPerformed

    private void updateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductActionPerformed
        try {
            int rowIndex = productTable.getSelectedRow();
            Long selectedRow = (Long) productTable.getValueAt(rowIndex, 0);
            EditProduct editProduct = new EditProduct(dao, selectedRow);
            editProduct.setVisible(true);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Hər hansı bir sətri seçin !!!");
        }

    }//GEN-LAST:event_updateProductActionPerformed

    private void deleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductActionPerformed
        try {
            int rowIndex = productTable.getSelectedRow();
            Long selectedRow = (Long) productTable.getValueAt(rowIndex, 0);

            int isDeleteMsg = JOptionPane.showConfirmDialog(null, "Əminsən?", "Sətri sil", JOptionPane.YES_NO_OPTION);
            if (isDeleteMsg == JOptionPane.YES_OPTION) {
                boolean isDelete = dao.deleteProduct(selectedRow);
                if (isDelete) {
                    JOptionPane.showMessageDialog(null, "Silindi...");
                    List<Product> productList = dao.getProductList();
                    ViewProductListInTable(productList);
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(CalcFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteProductActionPerformed

    private void searchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductActionPerformed
        try {
            String keyword = searchProductTxt.getText();
            List<Product> searchProductList = dao.searcProducts(keyword);
            ViewProductListInTable(searchProductList);
        } catch (Exception ex) {
            Logger.getLogger(CalcFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchProductActionPerformed

    private void searchProductTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchProductTxtKeyReleased
        searchProductActionPerformed(null);
    }//GEN-LAST:event_searchProductTxtKeyReleased

    private void searchAdvancedProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAdvancedProductActionPerformed
        try {
            AdvancedSearch as = new AdvancedSearch();
            String minSayTxt = minSay.getText();
            String maxSayTxt = maxSay.getText();
            String beginPriceTxt = beginPrice.getText();
            String endPriceTxt = endPrice.getText();
            as.setMinSay(minSayTxt);
            as.setMaxSay(maxSayTxt);
            as.setBeginPrice(beginPriceTxt);
            as.setEndPrice(endPriceTxt);

            List<Product> productList = dao.advancedSearchProduct(as);
            ViewProductListInTable(productList);
        } catch (Exception ex) {
            Logger.getLogger(CalcFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_searchAdvancedProductActionPerformed

    void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(64, 43, 100));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private com.toedter.calendar.JDateChooser beginDate;
    private javax.swing.JTextField beginPrice;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel calcBtn;
    private javax.swing.JLabel calcIcon;
    private javax.swing.JTable calcTable;
    private javax.swing.JLabel calcText;
    private javax.swing.JPanel content;
    private javax.swing.JButton deleteProduct;
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JTextField endPrice;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JTextField gainTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JLabel loginIcon;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel masaBtn;
    private javax.swing.JComboBox masaCombo;
    private javax.swing.JTextField maxSay;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuBtn;
    private javax.swing.JLabel menuIcon;
    private javax.swing.JLabel menuText;
    private javax.swing.JTextField minSay;
    private javax.swing.JPanel orderBtn;
    private javax.swing.JLabel orderIcon;
    private javax.swing.JLabel orderText;
    private javax.swing.JTable productTable;
    private javax.swing.JButton searchAdvancedPaid;
    private javax.swing.JButton searchAdvancedProduct;
    private javax.swing.JButton searchProduct;
    private javax.swing.JTextField searchProductTxt;
    private javax.swing.JPanel seperator;
    private javax.swing.JLabel tableIcon;
    private javax.swing.JLabel tableText;
    private javax.swing.JButton updateProduct;
    // End of variables declaration//GEN-END:variables

    private void ViewPaidListInTable(List<Paid> paidList) {
        DefaultTableModel table = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };

        calcTable.setModel(table);
        table.addColumn("Id");
        table.addColumn("№");
        table.addColumn("Masa");
        table.addColumn("Hesab");
        table.addColumn("Tarix");

        for (Paid paid : paidList) {
            Object data[] = new Object[]{
                paid.getId(), paid.getRownum(), paid.getSifarisMasa().getCafeTable().getName(),
                paid.getPrice(), paid.getPaidDate()
            };
            table.addRow(data);
        }
        calcTable.getColumnModel().getColumn(0).setMinWidth(0);
        calcTable.getColumnModel().getColumn(0).setMaxWidth(0);
        calcTable.getColumnModel().getColumn(0).setWidth(0);

    }

    private void ViewMasaInCombo(List<CafeTable> masaList) {
        DefaultComboBoxModel model = (DefaultComboBoxModel) masaCombo.getModel();
        for (CafeTable masa : masaList) {
            model.addElement(new Item(masa.getId(), masa.getName() + "--" + masa.getTablePeople() + " nəfərlik"));
        }
        model.setSelectedItem(new Item((long) 0, "Masa Seç"));
    }

    private void ViewProductListInTable(List<Product> productList) {
        DefaultTableModel table = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };

        productTable.setModel(table);
        table.addColumn("Id");
        table.addColumn("№");
        table.addColumn("Adı");
        table.addColumn("Sayı");
        table.addColumn("Qiyməti");

        for (Product product : productList) {
            Object data[] = new Object[]{
                product.getId(), product.getRownum(), product.getProductName(),
                product.getSay(), product.getPrice()
            };
            table.addRow(data);
        }
        productTable.getColumnModel().getColumn(0).setMinWidth(0);
        productTable.getColumnModel().getColumn(0).setMaxWidth(0);
        productTable.getColumnModel().getColumn(0).setWidth(0);

    }
}
