package cafemain;

import dao.DaoImpl;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.CafeTable;

public class MainFrame extends javax.swing.JFrame {
    
    private DaoImpl dao;
    private int id;
    private String globBtnName = "0";
    
    public MainFrame() {
        initComponents();
        
    }
    
    MainFrame(DaoImpl dao) {
        initComponents();
        this.dao = dao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masaCheckGroup = new javax.swing.ButtonGroup();
        kabinetCheckGroup = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        seperator = new javax.swing.JPanel();
        masaBtn = new javax.swing.JPanel();
        tableIcon = new javax.swing.JLabel();
        tableText = new javax.swing.JLabel();
        menuBtn = new javax.swing.JPanel();
        menuIcon = new javax.swing.JLabel();
        menuText = new javax.swing.JLabel();
        orderBtn = new javax.swing.JPanel();
        orderIcon = new javax.swing.JLabel();
        orderText = new javax.swing.JLabel();
        calcBtn = new javax.swing.JPanel();
        calcIcon = new javax.swing.JLabel();
        calcText = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitIcon = new javax.swing.JLabel();
        loginBtn = new javax.swing.JPanel();
        loginIcon = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emptyCheck = new javax.swing.JCheckBox();
        allTableCheck = new javax.swing.JCheckBox();
        masa11btn = new javax.swing.JButton();
        masa12btn = new javax.swing.JButton();
        masa13btn = new javax.swing.JButton();
        masa14btn = new javax.swing.JButton();
        masa15btn = new javax.swing.JButton();
        masa18btn = new javax.swing.JButton();
        masa16btn = new javax.swing.JButton();
        masa19btn = new javax.swing.JButton();
        masa10btn = new javax.swing.JButton();
        masa9btn = new javax.swing.JButton();
        masa8btn = new javax.swing.JButton();
        masa7btn = new javax.swing.JButton();
        masa17btn = new javax.swing.JButton();
        masa5btn = new javax.swing.JButton();
        masa4btn = new javax.swing.JButton();
        masa3btn = new javax.swing.JButton();
        masa2btn = new javax.swing.JButton();
        masa1btn = new javax.swing.JButton();
        masa6btn = new javax.swing.JButton();
        masa20btn = new javax.swing.JButton();
        for4peopleText = new javax.swing.JLabel();
        for2peopleText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cafe");
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(54, 33, 89));
        menu.setPreferredSize(new java.awt.Dimension(1200, 600));

        logo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setText("KeepEating");
        logo.setToolTipText("");

        seperator.setBackground(new java.awt.Color(255, 255, 255));
        seperator.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        seperator.setInheritsPopupMenu(true);

        javax.swing.GroupLayout seperatorLayout = new javax.swing.GroupLayout(seperator);
        seperator.setLayout(seperatorLayout);
        seperatorLayout.setHorizontalGroup(
            seperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        seperatorLayout.setVerticalGroup(
            seperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        masaBtn.setBackground(new java.awt.Color(85, 65, 118));
        masaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masaBtnMousePressed(evt);
            }
        });

        tableIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Restaurant Table_45px.png")); // NOI18N

        tableText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tableText.setForeground(new java.awt.Color(255, 255, 255));
        tableText.setText("MASALAR");

        javax.swing.GroupLayout masaBtnLayout = new javax.swing.GroupLayout(masaBtn);
        masaBtn.setLayout(masaBtnLayout);
        masaBtnLayout.setHorizontalGroup(
            masaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masaBtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tableIcon)
                .addGap(18, 18, 18)
                .addComponent(tableText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        masaBtnLayout.setVerticalGroup(
            masaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masaBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );

        menuBtn.setBackground(new java.awt.Color(54, 33, 89));
        menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuBtnMousePressed(evt);
            }
        });

        menuIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Restaurant Menu_45px.png")); // NOI18N

        menuText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        menuText.setForeground(new java.awt.Color(255, 255, 255));
        menuText.setText("MENYU");

        javax.swing.GroupLayout menuBtnLayout = new javax.swing.GroupLayout(menuBtn);
        menuBtn.setLayout(menuBtnLayout);
        menuBtnLayout.setHorizontalGroup(
            menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(menuIcon)
                .addGap(18, 18, 18)
                .addComponent(menuText, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBtnLayout.setVerticalGroup(
            menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnLayout.createSequentialGroup()
                .addGroup(menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        orderBtn.setBackground(new java.awt.Color(54, 33, 89));
        orderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orderBtnMousePressed(evt);
            }
        });

        orderIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Order History_45px.png")); // NOI18N

        orderText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orderText.setForeground(new java.awt.Color(255, 255, 255));
        orderText.setText("SİFARİŞ");

        javax.swing.GroupLayout orderBtnLayout = new javax.swing.GroupLayout(orderBtn);
        orderBtn.setLayout(orderBtnLayout);
        orderBtnLayout.setHorizontalGroup(
            orderBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderBtnLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(orderIcon)
                .addGap(18, 18, 18)
                .addComponent(orderText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderBtnLayout.setVerticalGroup(
            orderBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addComponent(orderText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        calcBtn.setBackground(new java.awt.Color(54, 33, 89));
        calcBtn.setPreferredSize(new java.awt.Dimension(176, 67));
        calcBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                calcBtnMousePressed(evt);
            }
        });

        calcIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Calculator_45px.png")); // NOI18N

        calcText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        calcText.setForeground(new java.awt.Color(255, 255, 255));
        calcText.setText("HESABAT");

        javax.swing.GroupLayout calcBtnLayout = new javax.swing.GroupLayout(calcBtn);
        calcBtn.setLayout(calcBtnLayout);
        calcBtnLayout.setHorizontalGroup(
            calcBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcBtnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(calcIcon)
                .addGap(18, 18, 18)
                .addComponent(calcText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calcBtnLayout.setVerticalGroup(
            calcBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calcIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addComponent(calcText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        exitBtn.setBackground(new java.awt.Color(85, 65, 118));
        exitBtn.setPreferredSize(new java.awt.Dimension(122, 56));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitBtnMousePressed(evt);
            }
        });

        exitIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Exit_45pxNew.png")); // NOI18N

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(exitIcon)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(exitIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        loginBtn.setBackground(new java.awt.Color(85, 65, 118));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtnMousePressed(evt);
            }
        });

        loginIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Person_45px.png")); // NOI18N

        javax.swing.GroupLayout loginBtnLayout = new javax.swing.GroupLayout(loginBtn);
        loginBtn.setLayout(loginBtnLayout);
        loginBtnLayout.setHorizontalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBtnLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(loginIcon)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        loginBtnLayout.setVerticalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(calcBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(masaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bg.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 660));

        content.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        jLabel1.setText("MASALAR");

        emptyCheck.setBackground(new java.awt.Color(255, 255, 255));
        masaCheckGroup.add(emptyCheck);
        emptyCheck.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emptyCheck.setText("Boş Masalar");
        emptyCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyCheckActionPerformed(evt);
            }
        });

        allTableCheck.setBackground(new java.awt.Color(255, 255, 255));
        masaCheckGroup.add(allTableCheck);
        allTableCheck.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        allTableCheck.setText("Masalar");
        allTableCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTableCheckActionPerformed(evt);
            }
        });

        masa11btn.setBackground(new java.awt.Color(54, 33, 89));
        masa11btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa11btn.setForeground(new java.awt.Color(255, 255, 255));
        masa11btn.setText("MASA 11");
        masa11btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa11btnActionPerformed(evt);
            }
        });

        masa12btn.setBackground(new java.awt.Color(54, 33, 89));
        masa12btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa12btn.setForeground(new java.awt.Color(255, 255, 255));
        masa12btn.setText("MASA 12");
        masa12btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa12btnActionPerformed(evt);
            }
        });

        masa13btn.setBackground(new java.awt.Color(54, 33, 89));
        masa13btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa13btn.setForeground(new java.awt.Color(255, 255, 255));
        masa13btn.setText("MASA 13");
        masa13btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa13btnActionPerformed(evt);
            }
        });

        masa14btn.setBackground(new java.awt.Color(54, 33, 89));
        masa14btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa14btn.setForeground(new java.awt.Color(255, 255, 255));
        masa14btn.setText("MASA 14");
        masa14btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa14btnActionPerformed(evt);
            }
        });

        masa15btn.setBackground(new java.awt.Color(54, 33, 89));
        masa15btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa15btn.setForeground(new java.awt.Color(255, 255, 255));
        masa15btn.setText("MASA 15");
        masa15btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa15btnActionPerformed(evt);
            }
        });

        masa18btn.setBackground(new java.awt.Color(54, 33, 89));
        masa18btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa18btn.setForeground(new java.awt.Color(255, 255, 255));
        masa18btn.setText("MASA 18");
        masa18btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa18btnActionPerformed(evt);
            }
        });

        masa16btn.setBackground(new java.awt.Color(54, 33, 89));
        masa16btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa16btn.setForeground(new java.awt.Color(255, 255, 255));
        masa16btn.setText("MASA 16");
        masa16btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa16btnActionPerformed(evt);
            }
        });

        masa19btn.setBackground(new java.awt.Color(54, 33, 89));
        masa19btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa19btn.setForeground(new java.awt.Color(255, 255, 255));
        masa19btn.setText("MASA 19");
        masa19btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa19btnActionPerformed(evt);
            }
        });

        masa10btn.setBackground(new java.awt.Color(54, 33, 89));
        masa10btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa10btn.setForeground(new java.awt.Color(255, 255, 255));
        masa10btn.setText("MASA 10");
        masa10btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa10btnActionPerformed(evt);
            }
        });

        masa9btn.setBackground(new java.awt.Color(54, 33, 89));
        masa9btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa9btn.setForeground(new java.awt.Color(255, 255, 255));
        masa9btn.setText("MASA 9");
        masa9btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa9btnActionPerformed(evt);
            }
        });

        masa8btn.setBackground(new java.awt.Color(54, 33, 89));
        masa8btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa8btn.setForeground(new java.awt.Color(255, 255, 255));
        masa8btn.setText("MASA 8");
        masa8btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa8btnActionPerformed(evt);
            }
        });

        masa7btn.setBackground(new java.awt.Color(54, 33, 89));
        masa7btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa7btn.setForeground(new java.awt.Color(255, 255, 255));
        masa7btn.setText("MASA 7");
        masa7btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa7btnActionPerformed(evt);
            }
        });

        masa17btn.setBackground(new java.awt.Color(54, 33, 89));
        masa17btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa17btn.setForeground(new java.awt.Color(255, 255, 255));
        masa17btn.setText("MASA 17");
        masa17btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa17btnActionPerformed(evt);
            }
        });

        masa5btn.setBackground(new java.awt.Color(54, 33, 89));
        masa5btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa5btn.setForeground(new java.awt.Color(255, 255, 255));
        masa5btn.setText("MASA 5");

        masa4btn.setBackground(new java.awt.Color(54, 33, 89));
        masa4btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa4btn.setForeground(new java.awt.Color(255, 255, 255));
        masa4btn.setText("MASA 4");

        masa3btn.setBackground(new java.awt.Color(54, 33, 89));
        masa3btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa3btn.setForeground(new java.awt.Color(255, 255, 255));
        masa3btn.setText("MASA 3");

        masa2btn.setBackground(new java.awt.Color(54, 33, 89));
        masa2btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa2btn.setForeground(new java.awt.Color(255, 255, 255));
        masa2btn.setText("MASA 2");

        masa1btn.setBackground(new java.awt.Color(54, 33, 89));
        masa1btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa1btn.setForeground(new java.awt.Color(255, 255, 255));
        masa1btn.setText("MASA 1");
        masa1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa1btnActionPerformed(evt);
            }
        });

        masa6btn.setBackground(new java.awt.Color(54, 33, 89));
        masa6btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa6btn.setForeground(new java.awt.Color(255, 255, 255));
        masa6btn.setText("MASA 6");

        masa20btn.setBackground(new java.awt.Color(54, 33, 89));
        masa20btn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        masa20btn.setForeground(new java.awt.Color(255, 255, 255));
        masa20btn.setText("MASA 20");
        masa20btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa20btnActionPerformed(evt);
            }
        });

        for4peopleText.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        for4peopleText.setText("4 NƏFƏRLİK");

        for2peopleText.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        for2peopleText.setText("2 NƏFƏRLİK");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setText("6 NƏFƏRLİK");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setText("8 NƏFƏRLİK");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setText("10 NƏFƏRLİK");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentLayout.createSequentialGroup()
                                        .addComponent(for2peopleText)
                                        .addGap(39, 39, 39)
                                        .addComponent(masa1btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(contentLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(39, 39, 39)
                                        .addComponent(masa18btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(masa13btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(masa17btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)
                                .addComponent(masa16btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masa15btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(masa2btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masa3btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masa4btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(masa14btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(allTableCheck)
                                .addGap(18, 18, 18)
                                .addComponent(emptyCheck))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(40, 40, 40)
                                        .addComponent(masa9btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(masa10btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(masa11btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(masa12btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(masa19btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                        .addComponent(for4peopleText)
                                        .addGap(39, 39, 39)
                                        .addComponent(masa5btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(masa6btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(masa7btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(masa8btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(masa20btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 235, Short.MAX_VALUE)))
                        .addGap(82, 82, 82))))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emptyCheck)
                                    .addComponent(allTableCheck))))
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(masa1btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(masa2btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(masa3btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(masa4btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(masa17btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(for2peopleText)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(masa5btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(masa6btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(masa7btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(masa8btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(masa20btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(for4peopleText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(masa9btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(masa10btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(masa11btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(masa12btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(masa19btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(masa18btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(masa13btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(masa14btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masa15btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masa16btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1030, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void masaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaBtnMousePressed
        setColor(masaBtn);
        resetColor(menuBtn);
        resetColor(orderBtn);
        resetColor(calcBtn);
    }//GEN-LAST:event_masaBtnMousePressed

    private void menuBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnMousePressed
        setColor(menuBtn);
        resetColor(masaBtn);
        resetColor(orderBtn);
        resetColor(calcBtn);
        MenuFrame menuFrame = new MenuFrame(dao);
        menuFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBtnMousePressed

    private void orderBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderBtnMousePressed
        setColor(orderBtn);
        resetColor(menuBtn);
        resetColor(masaBtn);
        resetColor(calcBtn);
        OrderFrame frame = new OrderFrame(dao);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orderBtnMousePressed

    private void calcBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcBtnMousePressed
        setColor(calcBtn);
        resetColor(menuBtn);
        resetColor(orderBtn);
        resetColor(masaBtn);
        CalcFrame calcFrame = new CalcFrame(dao);
        calcFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_calcBtnMousePressed

    private void masa8btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa8btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa8btnActionPerformed

    private void masa7btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa7btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa7btnActionPerformed

    private void masa10btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa10btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa10btnActionPerformed

    private void masa11btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa11btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa11btnActionPerformed

    private void masa12btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa12btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa12btnActionPerformed

    private void masa13btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa13btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa13btnActionPerformed

    private void masa14btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa14btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa14btnActionPerformed

    private void masa9btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa9btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa9btnActionPerformed

    private void masa15btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa15btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa15btnActionPerformed

    private void masa18btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa18btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa18btnActionPerformed

    private void masa19btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa19btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa19btnActionPerformed

    private void masa20btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa20btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa20btnActionPerformed

    private void masa16btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa16btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa16btnActionPerformed

    private void masa17btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa17btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa17btnActionPerformed

    private void exitBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitBtnMousePressed

    private void loginBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMousePressed
        LoginFrame frame = new LoginFrame(dao);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginBtnMousePressed

    private void emptyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptyCheckActionPerformed
        try {
            List<CafeTable> cafeTableList = dao.getCafeTableList();
            for (CafeTable cafeTable : cafeTableList) {
                if (emptyCheck.isSelected()) {
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 1) {
                        masa1btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 2) {
                        masa2btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 3) {
                        masa3btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 4) {
                        masa4btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 5) {
                        masa5btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 6) {
                        masa6btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 7) {
                        masa7btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 8) {
                        masa8btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 9) {
                        masa9btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 10) {
                        masa10btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 11) {
                        masa11btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 12) {
                        masa12btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 13) {
                        masa13btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 14) {
                        masa14btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 15) {
                        masa15btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 16) {
                        masa16btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 17) {
                        masa17btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 18) {
                        masa18btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 19) {
                        masa19btn.setEnabled(false);
                    }
                    if (cafeTable.getTableStatus().getId() == 2 && cafeTable.getId() == 20) {
                        masa20btn.setEnabled(false);
                    }
                } else {
                    masa1btn.setEnabled(true);
                    masa2btn.setEnabled(true);
                    masa3btn.setEnabled(true);
                    masa4btn.setEnabled(true);
                    masa5btn.setEnabled(true);
                    masa6btn.setEnabled(true);
                    masa7btn.setEnabled(true);
                    masa8btn.setEnabled(true);
                    masa9btn.setEnabled(true);
                    masa10btn.setEnabled(true);
                }
                
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_emptyCheckActionPerformed

    private void masa1btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa1btnActionPerformed
        id = 1;
    }//GEN-LAST:event_masa1btnActionPerformed

    private void allTableCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTableCheckActionPerformed
        if (allTableCheck.isSelected()) {
            masa1btn.setEnabled(true);
            masa2btn.setEnabled(true);
            masa3btn.setEnabled(true);
            masa4btn.setEnabled(true);
            masa5btn.setEnabled(true);
            masa6btn.setEnabled(true);
            masa7btn.setEnabled(true);
            masa8btn.setEnabled(true);
            masa9btn.setEnabled(true);
            masa10btn.setEnabled(true);
            masa11btn.setEnabled(true);
            masa12btn.setEnabled(true);
            masa13btn.setEnabled(true);
            masa14btn.setEnabled(true);
            masa15btn.setEnabled(true);
            masa16btn.setEnabled(true);
            masa17btn.setEnabled(true);
            masa18btn.setEnabled(true);
            masa19btn.setEnabled(true);
            masa20btn.setEnabled(true);
        }
    }//GEN-LAST:event_allTableCheckActionPerformed
    
    void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));
    }
    
    void resetColor(JPanel panel) {
        panel.setBackground(new Color(64, 43, 100));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allTableCheck;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel calcBtn;
    private javax.swing.JLabel calcIcon;
    private javax.swing.JLabel calcText;
    private javax.swing.JPanel content;
    private javax.swing.JCheckBox emptyCheck;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JLabel for2peopleText;
    private javax.swing.JLabel for4peopleText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.ButtonGroup kabinetCheckGroup;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JLabel loginIcon;
    private javax.swing.JLabel logo;
    private javax.swing.JButton masa10btn;
    private javax.swing.JButton masa11btn;
    private javax.swing.JButton masa12btn;
    private javax.swing.JButton masa13btn;
    private javax.swing.JButton masa14btn;
    private javax.swing.JButton masa15btn;
    private javax.swing.JButton masa16btn;
    private javax.swing.JButton masa17btn;
    private javax.swing.JButton masa18btn;
    private javax.swing.JButton masa19btn;
    private javax.swing.JButton masa1btn;
    private javax.swing.JButton masa20btn;
    private javax.swing.JButton masa2btn;
    private javax.swing.JButton masa3btn;
    private javax.swing.JButton masa4btn;
    private javax.swing.JButton masa5btn;
    private javax.swing.JButton masa6btn;
    private javax.swing.JButton masa7btn;
    private javax.swing.JButton masa8btn;
    private javax.swing.JButton masa9btn;
    private javax.swing.JPanel masaBtn;
    private javax.swing.ButtonGroup masaCheckGroup;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuBtn;
    private javax.swing.JLabel menuIcon;
    private javax.swing.JLabel menuText;
    private javax.swing.JPanel orderBtn;
    private javax.swing.JLabel orderIcon;
    private javax.swing.JLabel orderText;
    private javax.swing.JPanel seperator;
    private javax.swing.JLabel tableIcon;
    private javax.swing.JLabel tableText;
    // End of variables declaration//GEN-END:variables
}
