package cafemain;

import dao.DaoImpl;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Menu;
import model.MenuIn;

public class MenuFrame extends javax.swing.JFrame {

    private DaoImpl dao;
    private String globBtnName = "0";
    private int id;

    public MenuFrame() {
        try {
            initComponents();

            setBackground(new Color(0, 0, 0, 0));

            menuTable.getTableHeader().setFont(new Font("Calibri", Font.PLAIN, 14));
            menuTable.getTableHeader().setOpaque(false);
            menuTable.getTableHeader().setBackground(new Color(54, 33, 89)); //[54,33,89]
            menuTable.getTableHeader().setForeground(new Color(0, 0, 0));
            menuTable.setRowHeight(25);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    MenuFrame(DaoImpl dao) {
        try {
            initComponents();
            this.dao = dao;
            yemeklbl.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        seperator = new javax.swing.JPanel();
        masaBtn = new javax.swing.JPanel();
        tableIcon = new javax.swing.JLabel();
        tableText = new javax.swing.JLabel();
        menuBtn = new javax.swing.JPanel();
        menuIcon = new javax.swing.JLabel();
        menuText = new javax.swing.JLabel();
        orderBtn = new javax.swing.JPanel();
        orderIcon = new javax.swing.JLabel();
        orderText = new javax.swing.JLabel();
        calcBtn = new javax.swing.JPanel();
        calcIcon = new javax.swing.JLabel();
        calcText = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitIcon = new javax.swing.JLabel();
        loginBtn = new javax.swing.JPanel();
        loginIcon = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        salatbtn = new javax.swing.JButton();
        yemekbtn = new javax.swing.JButton();
        qarnirbtn = new javax.swing.JButton();
        sorbabtn = new javax.swing.JButton();
        lahmacunbtn = new javax.swing.JButton();
        donerbtn = new javax.swing.JButton();
        ickibtn = new javax.swing.JButton();
        pizzabtn = new javax.swing.JButton();
        avropabtn = new javax.swing.JButton();
        xemirbtn = new javax.swing.JButton();
        pidebtn = new javax.swing.JButton();
        yemeklbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        menyuBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cafe");
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(54, 33, 89));

        logo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setText("KeepEating");
        logo.setToolTipText("");

        seperator.setBackground(new java.awt.Color(255, 255, 255));
        seperator.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        seperator.setInheritsPopupMenu(true);

        javax.swing.GroupLayout seperatorLayout = new javax.swing.GroupLayout(seperator);
        seperator.setLayout(seperatorLayout);
        seperatorLayout.setHorizontalGroup(
            seperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        seperatorLayout.setVerticalGroup(
            seperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        masaBtn.setBackground(new java.awt.Color(54, 33, 89));
        masaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masaBtnMousePressed(evt);
            }
        });

        tableIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Restaurant Table_45px.png")); // NOI18N

        tableText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tableText.setForeground(new java.awt.Color(255, 255, 255));
        tableText.setText("MASALAR");

        javax.swing.GroupLayout masaBtnLayout = new javax.swing.GroupLayout(masaBtn);
        masaBtn.setLayout(masaBtnLayout);
        masaBtnLayout.setHorizontalGroup(
            masaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masaBtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tableIcon)
                .addGap(18, 18, 18)
                .addComponent(tableText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        masaBtnLayout.setVerticalGroup(
            masaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masaBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );

        menuBtn.setBackground(new java.awt.Color(85, 65, 118));
        menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuBtnMousePressed(evt);
            }
        });

        menuIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Restaurant Menu_45px.png")); // NOI18N

        menuText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        menuText.setForeground(new java.awt.Color(255, 255, 255));
        menuText.setText("MENYU");

        javax.swing.GroupLayout menuBtnLayout = new javax.swing.GroupLayout(menuBtn);
        menuBtn.setLayout(menuBtnLayout);
        menuBtnLayout.setHorizontalGroup(
            menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(menuIcon)
                .addGap(18, 18, 18)
                .addComponent(menuText, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBtnLayout.setVerticalGroup(
            menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnLayout.createSequentialGroup()
                .addGroup(menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        orderBtn.setBackground(new java.awt.Color(54, 33, 89));
        orderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orderBtnMousePressed(evt);
            }
        });

        orderIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Order History_45px.png")); // NOI18N

        orderText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orderText.setForeground(new java.awt.Color(255, 255, 255));
        orderText.setText("SİFARİŞ");

        javax.swing.GroupLayout orderBtnLayout = new javax.swing.GroupLayout(orderBtn);
        orderBtn.setLayout(orderBtnLayout);
        orderBtnLayout.setHorizontalGroup(
            orderBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderBtnLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(orderIcon)
                .addGap(18, 18, 18)
                .addComponent(orderText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderBtnLayout.setVerticalGroup(
            orderBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addComponent(orderText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        calcBtn.setBackground(new java.awt.Color(54, 33, 89));
        calcBtn.setPreferredSize(new java.awt.Dimension(176, 67));
        calcBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                calcBtnMousePressed(evt);
            }
        });

        calcIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Calculator_45px.png")); // NOI18N

        calcText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        calcText.setForeground(new java.awt.Color(255, 255, 255));
        calcText.setText("HESABAT");

        javax.swing.GroupLayout calcBtnLayout = new javax.swing.GroupLayout(calcBtn);
        calcBtn.setLayout(calcBtnLayout);
        calcBtnLayout.setHorizontalGroup(
            calcBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcBtnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(calcIcon)
                .addGap(18, 18, 18)
                .addComponent(calcText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calcBtnLayout.setVerticalGroup(
            calcBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calcIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addComponent(calcText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        exitBtn.setBackground(new java.awt.Color(85, 65, 118));
        exitBtn.setPreferredSize(new java.awt.Dimension(122, 56));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitBtnMousePressed(evt);
            }
        });

        exitIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Exit_45pxNew.png")); // NOI18N

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(exitIcon)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(exitIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        loginBtn.setBackground(new java.awt.Color(85, 65, 118));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtnMousePressed(evt);
            }
        });

        loginIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Person_45px.png")); // NOI18N

        javax.swing.GroupLayout loginBtnLayout = new javax.swing.GroupLayout(loginBtn);
        loginBtn.setLayout(loginBtnLayout);
        loginBtnLayout.setHorizontalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBtnLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(loginIcon)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        loginBtnLayout.setVerticalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(calcBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(masaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bg.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 660));

        content.setBackground(new java.awt.Color(255, 255, 255));

        salatbtn.setBackground(new java.awt.Color(54, 33, 89));
        salatbtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        salatbtn.setForeground(new java.awt.Color(255, 255, 255));
        salatbtn.setText("SALATLAR");
        salatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salatbtnActionPerformed(evt);
            }
        });

        yemekbtn.setBackground(new java.awt.Color(54, 33, 89));
        yemekbtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        yemekbtn.setForeground(new java.awt.Color(255, 255, 255));
        yemekbtn.setText("YEMƏKLƏR");
        yemekbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yemekbtnActionPerformed(evt);
            }
        });

        qarnirbtn.setBackground(new java.awt.Color(54, 33, 89));
        qarnirbtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        qarnirbtn.setForeground(new java.awt.Color(255, 255, 255));
        qarnirbtn.setText("QARNİRLƏR");
        qarnirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qarnirbtnActionPerformed(evt);
            }
        });

        sorbabtn.setBackground(new java.awt.Color(54, 33, 89));
        sorbabtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        sorbabtn.setForeground(new java.awt.Color(255, 255, 255));
        sorbabtn.setText("ŞORBALAR");
        sorbabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sorbabtnActionPerformed(evt);
            }
        });

        lahmacunbtn.setBackground(new java.awt.Color(54, 33, 89));
        lahmacunbtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lahmacunbtn.setForeground(new java.awt.Color(255, 255, 255));
        lahmacunbtn.setText("LAHMACUN");
        lahmacunbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lahmacunbtnActionPerformed(evt);
            }
        });

        donerbtn.setBackground(new java.awt.Color(54, 33, 89));
        donerbtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        donerbtn.setForeground(new java.awt.Color(255, 255, 255));
        donerbtn.setText("DÖNƏR");
        donerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donerbtnActionPerformed(evt);
            }
        });

        ickibtn.setBackground(new java.awt.Color(54, 33, 89));
        ickibtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ickibtn.setForeground(new java.awt.Color(255, 255, 255));
        ickibtn.setText("İÇKİLƏR");
        ickibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ickibtnActionPerformed(evt);
            }
        });

        pizzabtn.setBackground(new java.awt.Color(54, 33, 89));
        pizzabtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pizzabtn.setForeground(new java.awt.Color(255, 255, 255));
        pizzabtn.setText("PİZZA");
        pizzabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzabtnActionPerformed(evt);
            }
        });

        avropabtn.setBackground(new java.awt.Color(54, 33, 89));
        avropabtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        avropabtn.setForeground(new java.awt.Color(255, 255, 255));
        avropabtn.setText("AVROPA YEMƏKLƏRi");
        avropabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avropabtnActionPerformed(evt);
            }
        });

        xemirbtn.setBackground(new java.awt.Color(54, 33, 89));
        xemirbtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        xemirbtn.setForeground(new java.awt.Color(255, 255, 255));
        xemirbtn.setText("XƏMİR YEMƏKLƏRİ");
        xemirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemirbtnActionPerformed(evt);
            }
        });

        pidebtn.setBackground(new java.awt.Color(54, 33, 89));
        pidebtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pidebtn.setForeground(new java.awt.Color(255, 255, 255));
        pidebtn.setText("PİDƏ");
        pidebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidebtnActionPerformed(evt);
            }
        });

        yemeklbl.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        yemeklbl.setText("YEMƏKLƏR");

        menuTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        menuTable.setFocusable(false);
        menuTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        menuTable.setRowHeight(25);
        menuTable.setSelectionBackground(new java.awt.Color(54, 33, 89));
        menuTable.getTableHeader().setReorderingAllowed(false);
        menuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(menuTable);

        menyuBtn.setBackground(new java.awt.Color(54, 33, 89));
        menyuBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        menyuBtn.setForeground(new java.awt.Color(255, 255, 255));
        menyuBtn.setText("MENYU");
        menyuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menyuBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(54, 33, 89));
        addBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Add New_35px.png")); // NOI18N
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(54, 33, 89));
        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Update_35pxÜhite.png")); // NOI18N
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(54, 33, 89));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Delete_35pxÜhite.png")); // NOI18N
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchTxt.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(54, 33, 89));
        searchBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Search_35px.png")); // NOI18N
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ickibtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pizzabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yemekbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(salatbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(menyuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pidebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(donerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qarnirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(xemirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(avropabtn)
                        .addComponent(sorbabtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lahmacunbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(yemeklbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteBtn)
                        .addGap(18, 18, 18)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addBtn)
                            .addComponent(yemeklbl)
                            .addComponent(deleteBtn)
                            .addComponent(updateBtn)
                            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(searchBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(searchTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menyuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yemekbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pidebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(donerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qarnirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xemirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avropabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pizzabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ickibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sorbabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lahmacunbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1030, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void masaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaBtnMousePressed
        setColor(masaBtn);
        resetColor(menuBtn);
        resetColor(orderBtn);
        resetColor(calcBtn);
        MainFrame mainFrame = new MainFrame(dao);
        mainFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_masaBtnMousePressed

    private void menuBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnMousePressed
        setColor(menuBtn);
        resetColor(masaBtn);
        resetColor(orderBtn);
        resetColor(calcBtn);
    }//GEN-LAST:event_menuBtnMousePressed

    private void orderBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderBtnMousePressed
        setColor(orderBtn);
        resetColor(menuBtn);
        resetColor(masaBtn);
        resetColor(calcBtn);
        OrderFrame frame = new OrderFrame(dao);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orderBtnMousePressed

    private void calcBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcBtnMousePressed
        setColor(calcBtn);
        resetColor(menuBtn);
        resetColor(orderBtn);
        resetColor(masaBtn);
        CalcFrame calcFrame = new CalcFrame(dao);
        calcFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_calcBtnMousePressed

    private void exitBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitBtnMousePressed

    private void loginBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMousePressed
        LoginFrame frame = new LoginFrame(dao);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginBtnMousePressed

    private void salatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salatbtnActionPerformed
        try {
            globBtnName = "salat";
            id = 1;
            yemeklbl.setVisible(true);
            yemeklbl.setText("Salatlar");
            List<MenuIn> menuInList = dao.getMenuInListById((long) id);
            ViewYemekInTable(menuInList);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_salatbtnActionPerformed

    private void yemekbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yemekbtnActionPerformed
        try {
            globBtnName = "yemek";
            id = 2;
            yemeklbl.setVisible(true);
            yemeklbl.setText("Yeməklər");
            List<MenuIn> menuInList = dao.getMenuInListById((long) id);
            ViewYemekInTable(menuInList);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yemekbtnActionPerformed

    private void qarnirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qarnirbtnActionPerformed
        try {
            globBtnName = "qarnir";
            id = 3;
            yemeklbl.setVisible(true);
            yemeklbl.setText("Qarnirlər");
            List<MenuIn> menuInList = dao.getMenuInListById((long) id);
            ViewYemekInTable(menuInList);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_qarnirbtnActionPerformed

    private void sorbabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sorbabtnActionPerformed
        try {
            globBtnName = "sorba";
            id = 4;
            yemeklbl.setVisible(true);
            yemeklbl.setText("Şorbalar");
            List<MenuIn> menuInList = dao.getMenuInListById((long) id);
            ViewYemekInTable(menuInList);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sorbabtnActionPerformed

    private void lahmacunbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lahmacunbtnActionPerformed
        try {
            globBtnName = "lahmacun";
            id = 5;
            yemeklbl.setVisible(true);
            yemeklbl.setText("Lahmacun");
            List<MenuIn> menuInList = dao.getMenuInListById((long) id);
            ViewYemekInTable(menuInList);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lahmacunbtnActionPerformed

    private void pidebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidebtnActionPerformed
        try {
            globBtnName = "pide";
            id = 6;
            yemeklbl.setVisible(true);
            yemeklbl.setText("Pidə");
            List<MenuIn> menuInList = dao.getMenuInListById((long) id);
            ViewYemekInTable(menuInList);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pidebtnActionPerformed

    private void donerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donerbtnActionPerformed
        try {
            globBtnName = "doner";
            id = 7;
            yemeklbl.setVisible(true);
            yemeklbl.setText("Dönər");
            List<MenuIn> menuInList = dao.getMenuInListById((long) id);
            ViewYemekInTable(menuInList);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_donerbtnActionPerformed

    private void avropabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avropabtnActionPerformed
        try {
            globBtnName = "avropaYemek";
            id = 8;
            yemeklbl.setVisible(true);
            yemeklbl.setText("Avropa Yeməkləri");
            List<MenuIn> menuInList = dao.getMenuInListById((long) id);
            ViewYemekInTable(menuInList);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_avropabtnActionPerformed

    private void xemirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemirbtnActionPerformed
        try {
            globBtnName = "xemirYemek";
            id = 9;
            yemeklbl.setVisible(true);
            yemeklbl.setText("Xəmir Yeməkləri");
            List<MenuIn> menuInList = dao.getMenuInListById((long) id);
            ViewYemekInTable(menuInList);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_xemirbtnActionPerformed

    private void pizzabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzabtnActionPerformed
        try {
            globBtnName = "pizza";
            id = 10;
            yemeklbl.setVisible(true);
            yemeklbl.setText("Pizza");
            List<MenuIn> menuInList = dao.getMenuInListById((long) id);
            ViewYemekInTable(menuInList);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pizzabtnActionPerformed

    private void ickibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ickibtnActionPerformed
        try {
            globBtnName = "icki";
            id = 11;
            yemeklbl.setVisible(true);
            yemeklbl.setText("İçkilər");
            List<MenuIn> menuInList = dao.getMenuInListById((long) id);
            ViewYemekInTable(menuInList);
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ickibtnActionPerformed

    private void menyuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menyuBtnActionPerformed
        try {
            globBtnName = "menu";
            List<Menu> menuList = dao.getMenuList();
            menuTable(menuList);
            yemeklbl.setVisible(true);
            yemeklbl.setText("Menyu");
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menyuBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        switch (globBtnName) {
            case "menu":
                id = 0;
                AddMenu addMenu0 = new AddMenu(dao, id);
                addMenu0.setVisible(true);
                menyuBtnActionPerformed(evt);
                break;
            case "salat":
                AddMenu addMenu = new AddMenu(dao, id);
                addMenu.setVisible(true);
                salatbtnActionPerformed(evt);
                break;
            case "yemek":
                AddMenu addMenu1 = new AddMenu(dao, id);
                addMenu1.setVisible(true);
                yemekbtnActionPerformed(evt);
                break;
            case "qarnir":
                AddMenu addMenu2 = new AddMenu(dao, id);
                addMenu2.setVisible(true);
                qarnirbtnActionPerformed(evt);
                break;
            case "sorba":
                AddMenu addMenu3 = new AddMenu(dao, id);
                addMenu3.setVisible(true);
                sorbabtnActionPerformed(evt);
                break;
            case "lahmacun":
                AddMenu addMenu4 = new AddMenu(dao, id);
                addMenu4.setVisible(true);
                lahmacunbtnActionPerformed(evt);
                break;
            case "pide":
                AddMenu addMenu5 = new AddMenu(dao, id);
                addMenu5.setVisible(true);
                pidebtnActionPerformed(evt);
                break;
            case "doner":
                AddMenu addMenu6 = new AddMenu(dao, id);
                addMenu6.setVisible(true);
                donerbtnActionPerformed(evt);
                break;
            case "avropaYemek":
                AddMenu addMenu7 = new AddMenu(dao, id);
                addMenu7.setVisible(true);
                avropabtnActionPerformed(evt);
                break;
            case "xemirYemek":
                AddMenu addMenu8 = new AddMenu(dao, id);
                addMenu8.setVisible(true);
                xemirbtnActionPerformed(evt);
                break;
            case "pizza":
                AddMenu addMenu9 = new AddMenu(dao, id);
                addMenu9.setVisible(true);
                pizzabtnActionPerformed(evt);
                break;
            case "icki":
                AddMenu addMenu10 = new AddMenu(dao, id);
                addMenu10.setVisible(true);
                ickibtnActionPerformed(evt);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Hər hansi bir menyunu seçın !!!");
                break;
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
            int rowIndex = menuTable.getSelectedRow();
            Long selectedRow = (Long) menuTable.getValueAt(rowIndex, 0);
            switch (globBtnName) {
                case "menu":
                    id = 0;
                    EditMenu editMenu = new EditMenu(selectedRow, id);
                    editMenu.setVisible(true);
                    menyuBtnActionPerformed(evt);
                    break;
                case "salat":
                    EditMenu editMenu1 = new EditMenu(selectedRow, id);
                    editMenu1.setVisible(true);
                    salatbtnActionPerformed(evt);
                    break;
                case "yemek":
                    EditMenu editMenu2 = new EditMenu(selectedRow, id);
                    editMenu2.setVisible(true);
                    yemekbtnActionPerformed(evt);
                    break;
                case "qarnir":
                    EditMenu editMenu3 = new EditMenu(selectedRow, id);
                    editMenu3.setVisible(true);
                    qarnirbtnActionPerformed(evt);
                    break;
                case "sorba":
                    EditMenu editMenu4 = new EditMenu(selectedRow, id);
                    editMenu4.setVisible(true);
                    sorbabtnActionPerformed(evt);
                    break;
                case "lahmacun":
                    EditMenu editMenu5 = new EditMenu(selectedRow, id);
                    editMenu5.setVisible(true);
                    lahmacunbtnActionPerformed(evt);
                    break;
                case "pide":
                    EditMenu editMenu6 = new EditMenu(selectedRow, id);
                    editMenu6.setVisible(true);
                    pidebtnActionPerformed(evt);
                    break;
                case "doner":
                    EditMenu editMenu7 = new EditMenu(selectedRow, id);
                    editMenu7.setVisible(true);
                    donerbtnActionPerformed(evt);
                    break;
                case "avropaYemek":
                    EditMenu editMenu8 = new EditMenu(selectedRow, id);
                    editMenu8.setVisible(true);
                    avropabtnActionPerformed(evt);
                    break;
                case "xemirYemek":
                    EditMenu editMenu9 = new EditMenu(selectedRow, id);
                    editMenu9.setVisible(true);
                    xemirbtnActionPerformed(evt);
                    break;
                case "pizza":
                    EditMenu editMenu10 = new EditMenu(selectedRow, id);
                    editMenu10.setVisible(true);
                    pizzabtnActionPerformed(evt);
                    break;
                case "icki":
                    EditMenu editMenu11 = new EditMenu(selectedRow, id);
                    editMenu11.setVisible(true);
                    ickibtnActionPerformed(evt);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Hər hansi bir menyunu seçın !!!");
                    break;
            }

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Hər hansi bir sətri seçin!!!");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try {
            int rowIndex = menuTable.getSelectedRow();
            Long selectedRow = (Long) menuTable.getValueAt(rowIndex, 0);
            switch (globBtnName) {
                case "menu":
                    id = 0;
                    int isDeleteMsg = JOptionPane.showConfirmDialog(null, "Eminsen?", "Sətri sil", JOptionPane.YES_NO_OPTION);
                    if (isDeleteMsg == JOptionPane.YES_OPTION) {
                        boolean isDelete = dao.deleteMenu(selectedRow);
                        if (isDelete) {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silindi...");
                            menyuBtnActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silinmedi...");
                        }
                    }
                    break;
                case "salat":
                    int isDeleteMsg1 = JOptionPane.showConfirmDialog(null, "Eminsen?", "Yeməyi sil", JOptionPane.YES_NO_OPTION);
                    if (isDeleteMsg1 == JOptionPane.YES_OPTION) {
                        boolean isDelete = dao.deleteMenuIn(selectedRow, (long) id);
                        if (isDelete) {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silindi...");
                            salatbtnActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silinmedi...");
                        }
                    }
                    break;
                case "yemek":
                    int isDeleteMsg2 = JOptionPane.showConfirmDialog(null, "Eminsen?", "Yeməyi sil", JOptionPane.YES_NO_OPTION);
                    if (isDeleteMsg2 == JOptionPane.YES_OPTION) {
                        boolean isDelete = dao.deleteMenuIn(selectedRow, (long) id);
                        if (isDelete) {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silindi...");
                            yemekbtnActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silinmedi...");
                        }
                    }
                    break;
                case "qarnir":
                    int isDeleteMsg3 = JOptionPane.showConfirmDialog(null, "Eminsen?", "Yeməyi sil", JOptionPane.YES_NO_OPTION);
                    if (isDeleteMsg3 == JOptionPane.YES_OPTION) {
                        boolean isDelete = dao.deleteMenuIn(selectedRow, (long) id);
                        if (isDelete) {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silindi...");
                            qarnirbtnActionPerformed(evt);

                        } else {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silinmedi...");
                        }
                    }
                    break;
                case "sorba":
                    int isDeleteMsg4 = JOptionPane.showConfirmDialog(null, "Eminsen?", "Yeməyi sil", JOptionPane.YES_NO_OPTION);
                    if (isDeleteMsg4 == JOptionPane.YES_OPTION) {
                        boolean isDelete = dao.deleteMenuIn(selectedRow, (long) id);
                        if (isDelete) {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silindi...");
                            sorbabtnActionPerformed(evt);

                        } else {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silinmedi...");
                        }
                    }
                    break;
                case "lahmacun":
                    int isDeleteMsg5 = JOptionPane.showConfirmDialog(null, "Eminsen?", "Yeməyi sil", JOptionPane.YES_NO_OPTION);
                    if (isDeleteMsg5 == JOptionPane.YES_OPTION) {
                        boolean isDelete = dao.deleteMenuIn(selectedRow, (long) id);
                        if (isDelete) {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silindi...");
                            lahmacunbtnActionPerformed(evt);

                        } else {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silinmedi...");
                        }
                    }
                    break;
                case "pide":
                    int isDeleteMsg6 = JOptionPane.showConfirmDialog(null, "Eminsen?", "Yeməyi sil", JOptionPane.YES_NO_OPTION);
                    if (isDeleteMsg6 == JOptionPane.YES_OPTION) {
                        boolean isDelete = dao.deleteMenuIn(selectedRow, (long) id);
                        if (isDelete) {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silindi...");
                            pidebtnActionPerformed(evt);

                        } else {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silinmedi...");
                        }
                    }
                    break;
                case "doner":
                    int isDeleteMsg7 = JOptionPane.showConfirmDialog(null, "Eminsen?", "Yeməyi sil", JOptionPane.YES_NO_OPTION);
                    if (isDeleteMsg7 == JOptionPane.YES_OPTION) {
                        boolean isDelete = dao.deleteMenuIn(selectedRow, (long) id);
                        if (isDelete) {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silindi...");
                            donerbtnActionPerformed(evt);

                        } else {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silinmedi...");
                        }
                    }
                    break;
                case "avropaYemek":
                    int isDeleteMsg8 = JOptionPane.showConfirmDialog(null, "Eminsen?", "Yeməyi sil", JOptionPane.YES_NO_OPTION);
                    if (isDeleteMsg8 == JOptionPane.YES_OPTION) {
                        boolean isDelete = dao.deleteMenuIn(selectedRow, (long) id);
                        if (isDelete) {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silindi...");
                            avropabtnActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silinmedi...");
                        }
                    }
                    break;
                case "xemirYemek":
                    int isDeleteMsg9 = JOptionPane.showConfirmDialog(null, "Eminsen?", "Yeməyi sil", JOptionPane.YES_NO_OPTION);
                    if (isDeleteMsg9 == JOptionPane.YES_OPTION) {
                        boolean isDelete = dao.deleteMenuIn(selectedRow, (long) id);
                        if (isDelete) {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silindi...");
                            xemirbtnActionPerformed(evt);

                        } else {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silinmedi...");
                        }
                    }
                    break;
                case "pizza":
                    int isDeleteMsg10 = JOptionPane.showConfirmDialog(null, "Eminsen?", "Yeməyi sil", JOptionPane.YES_NO_OPTION);
                    if (isDeleteMsg10 == JOptionPane.YES_OPTION) {
                        boolean isDelete = dao.deleteMenuIn(selectedRow, (long) id);
                        if (isDelete) {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silindi...");
                            pizzabtnActionPerformed(evt);

                        } else {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silinmedi...");
                        }
                    }
                    break;
                case "icki":
                    int isDeleteMsg11 = JOptionPane.showConfirmDialog(null, "Eminsen?", "Yeməyi sil", JOptionPane.YES_NO_OPTION);
                    if (isDeleteMsg11 == JOptionPane.YES_OPTION) {
                        boolean isDelete = dao.deleteMenuIn(selectedRow, (long) id);
                        if (isDelete) {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silindi...");
                            ickibtnActionPerformed(evt);

                        } else {
                            JOptionPane.showMessageDialog(null, "Yemək Menyudan Silinmedi...");
                        }
                    }
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Hər hansi bir menyunu seçın !!!");
                    break;
            }

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Hər hansi bir sətri seçin!!!");
        } catch (Exception ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        if (id == 0) {
            try {
                String keyword = searchTxt.getText();
                List<Menu> menuList = dao.searchMenu(keyword);
                menuTable(menuList);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
            try {
                String keyword = searchTxt.getText();
                List<MenuIn> menuInList = dao.searchMenuIn(keyword, (long) id);
                ViewYemekInTable(menuInList);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtKeyPressed

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        searchBtnActionPerformed(null);
    }//GEN-LAST:event_searchTxtKeyReleased

    private void menuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTableMouseClicked
        if (evt.getClickCount() == 2) {
            updateBtnActionPerformed(null);
        }
    }//GEN-LAST:event_menuTableMouseClicked

    void setColor(JPanel panel
    ) {
        panel.setBackground(new Color(85, 65, 118));
    }

    void resetColor(JPanel panel
    ) {
        panel.setBackground(new Color(64, 43, 100));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton avropabtn;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel calcBtn;
    private javax.swing.JLabel calcIcon;
    private javax.swing.JLabel calcText;
    private javax.swing.JPanel content;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton donerbtn;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JButton ickibtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lahmacunbtn;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JLabel loginIcon;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel masaBtn;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuBtn;
    private javax.swing.JLabel menuIcon;
    private javax.swing.JTable menuTable;
    private javax.swing.JLabel menuText;
    private javax.swing.JButton menyuBtn;
    private javax.swing.JPanel orderBtn;
    private javax.swing.JLabel orderIcon;
    private javax.swing.JLabel orderText;
    private javax.swing.JButton pidebtn;
    private javax.swing.JButton pizzabtn;
    private javax.swing.JButton qarnirbtn;
    private javax.swing.JButton salatbtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JPanel seperator;
    private javax.swing.JButton sorbabtn;
    private javax.swing.JLabel tableIcon;
    private javax.swing.JLabel tableText;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton xemirbtn;
    private javax.swing.JButton yemekbtn;
    private javax.swing.JLabel yemeklbl;
    // End of variables declaration//GEN-END:variables

    private void menuTable(List<Menu> menuList) {
        DefaultTableModel table = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };

        menuTable.setModel(table);
        table.addColumn("Id");
        table.addColumn("№");
        table.addColumn("Menyu");

        for (Menu menu : menuList) {
            Object data[] = new Object[]{
                menu.getId(), menu.getRownum(), menu.getName()
            };
            table.addRow(data);
        }
        menuTable.getColumnModel().getColumn(0).setMinWidth(0);
        menuTable.getColumnModel().getColumn(0).setMaxWidth(0);
        menuTable.getColumnModel().getColumn(0).setWidth(0);

    }

    private void ViewYemekInTable(List<MenuIn> menuInList) {
        DefaultTableModel table = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };

        menuTable.setModel(table);
        table.addColumn("Id");
        table.addColumn("№");
        table.addColumn("Menyu Adı");
        table.addColumn("Yemək Adı");
        table.addColumn("Qiyməti");
        try {
            for (MenuIn menuIn : menuInList) {
                Object data[] = new Object[]{
                    menuIn.getId(), menuIn.getRownum(), menuIn.getMenu().getName(), menuIn.getMenyuInName(), menuIn.getPrice()
                };
                table.addRow(data);
            }

            menuTable.getColumnModel().getColumn(0).setMinWidth(0);
            menuTable.getColumnModel().getColumn(0).setMaxWidth(0);
            menuTable.getColumnModel().getColumn(0).setWidth(0);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
