package cafemain;

import dao.DaoImpl;
import java.awt.Color;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Sifaris_Masa;

public class OrderFrame extends javax.swing.JFrame {

    private DaoImpl dao;

    public OrderFrame() {
        initComponents();
    }

    OrderFrame(DaoImpl dao) {
        try {
            initComponents();
            this.dao = dao;
            List<Sifaris_Masa> sifarisMasaList = dao.getSifarisMasaList();
            ViewSifarisInTable(sifarisMasaList);
        } catch (Exception ex) {
            Logger.getLogger(OrderFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        seperator = new javax.swing.JPanel();
        masaBtn = new javax.swing.JPanel();
        tableIcon = new javax.swing.JLabel();
        tableText = new javax.swing.JLabel();
        menuBtn = new javax.swing.JPanel();
        menuIcon = new javax.swing.JLabel();
        menuText = new javax.swing.JLabel();
        orderBtn = new javax.swing.JPanel();
        orderIcon = new javax.swing.JLabel();
        orderText = new javax.swing.JLabel();
        calcBtn = new javax.swing.JPanel();
        calcIcon = new javax.swing.JLabel();
        calcText = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitIcon = new javax.swing.JLabel();
        loginBtn = new javax.swing.JPanel();
        loginIcon = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        addOrder = new javax.swing.JButton();
        editOrder = new javax.swing.JButton();
        deleteOrder = new javax.swing.JButton();
        paidOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cafe");
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(54, 33, 89));

        logo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setText("KeepEating");
        logo.setToolTipText("");

        seperator.setBackground(new java.awt.Color(255, 255, 255));
        seperator.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        seperator.setInheritsPopupMenu(true);

        javax.swing.GroupLayout seperatorLayout = new javax.swing.GroupLayout(seperator);
        seperator.setLayout(seperatorLayout);
        seperatorLayout.setHorizontalGroup(
            seperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        seperatorLayout.setVerticalGroup(
            seperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        masaBtn.setBackground(new java.awt.Color(54, 33, 89));
        masaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masaBtnMousePressed(evt);
            }
        });

        tableIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Restaurant Table_45px.png")); // NOI18N

        tableText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tableText.setForeground(new java.awt.Color(255, 255, 255));
        tableText.setText("MASALAR");

        javax.swing.GroupLayout masaBtnLayout = new javax.swing.GroupLayout(masaBtn);
        masaBtn.setLayout(masaBtnLayout);
        masaBtnLayout.setHorizontalGroup(
            masaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masaBtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tableIcon)
                .addGap(18, 18, 18)
                .addComponent(tableText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        masaBtnLayout.setVerticalGroup(
            masaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masaBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );

        menuBtn.setBackground(new java.awt.Color(54, 33, 89));
        menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuBtnMousePressed(evt);
            }
        });

        menuIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Restaurant Menu_45px.png")); // NOI18N

        menuText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        menuText.setForeground(new java.awt.Color(255, 255, 255));
        menuText.setText("MENYU");

        javax.swing.GroupLayout menuBtnLayout = new javax.swing.GroupLayout(menuBtn);
        menuBtn.setLayout(menuBtnLayout);
        menuBtnLayout.setHorizontalGroup(
            menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(menuIcon)
                .addGap(18, 18, 18)
                .addComponent(menuText, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuBtnLayout.setVerticalGroup(
            menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnLayout.createSequentialGroup()
                .addGroup(menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        orderBtn.setBackground(new java.awt.Color(85, 65, 118));
        orderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orderBtnMousePressed(evt);
            }
        });

        orderIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Order History_45px.png")); // NOI18N

        orderText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orderText.setForeground(new java.awt.Color(255, 255, 255));
        orderText.setText("SİFARİŞ");

        javax.swing.GroupLayout orderBtnLayout = new javax.swing.GroupLayout(orderBtn);
        orderBtn.setLayout(orderBtnLayout);
        orderBtnLayout.setHorizontalGroup(
            orderBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderBtnLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(orderIcon)
                .addGap(18, 18, 18)
                .addComponent(orderText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderBtnLayout.setVerticalGroup(
            orderBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addComponent(orderText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        calcBtn.setBackground(new java.awt.Color(54, 33, 89));
        calcBtn.setPreferredSize(new java.awt.Dimension(176, 67));
        calcBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                calcBtnMousePressed(evt);
            }
        });

        calcIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Calculator_45px.png")); // NOI18N

        calcText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        calcText.setForeground(new java.awt.Color(255, 255, 255));
        calcText.setText("HESABAT");

        javax.swing.GroupLayout calcBtnLayout = new javax.swing.GroupLayout(calcBtn);
        calcBtn.setLayout(calcBtnLayout);
        calcBtnLayout.setHorizontalGroup(
            calcBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcBtnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(calcIcon)
                .addGap(18, 18, 18)
                .addComponent(calcText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calcBtnLayout.setVerticalGroup(
            calcBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calcIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addComponent(calcText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        exitBtn.setBackground(new java.awt.Color(85, 65, 118));
        exitBtn.setPreferredSize(new java.awt.Dimension(122, 56));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitBtnMousePressed(evt);
            }
        });

        exitIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Exit_45pxNew.png")); // NOI18N

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(exitIcon)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        loginBtn.setBackground(new java.awt.Color(85, 65, 118));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBtnMousePressed(evt);
            }
        });

        loginIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\JAVA\\DESKTOP\\DESKTOP_IMG\\Person_45px.png")); // NOI18N

        javax.swing.GroupLayout loginBtnLayout = new javax.swing.GroupLayout(loginBtn);
        loginBtn.setLayout(loginBtnLayout);
        loginBtnLayout.setHorizontalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBtnLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(loginIcon)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        loginBtnLayout.setVerticalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(calcBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(masaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bg.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 660));

        content.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        jLabel1.setText("SİFARİŞ");

        orderTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        orderTable.setFocusable(false);
        orderTable.setRowHeight(25);
        orderTable.setSelectionBackground(new java.awt.Color(54, 33, 89));
        jScrollPane1.setViewportView(orderTable);

        addOrder.setBackground(new java.awt.Color(54, 33, 89));
        addOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addOrder.setForeground(new java.awt.Color(255, 255, 255));
        addOrder.setText("SİFARİŞ ƏLAVƏ ET");
        addOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderActionPerformed(evt);
            }
        });

        editOrder.setBackground(new java.awt.Color(54, 33, 89));
        editOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editOrder.setForeground(new java.awt.Color(255, 255, 255));
        editOrder.setText("DÜZƏLİŞ ET");
        editOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOrderActionPerformed(evt);
            }
        });

        deleteOrder.setBackground(new java.awt.Color(54, 33, 89));
        deleteOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteOrder.setForeground(new java.awt.Color(255, 255, 255));
        deleteOrder.setText("SİL");
        deleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrderActionPerformed(evt);
            }
        });

        paidOrder.setBackground(new java.awt.Color(54, 33, 89));
        paidOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paidOrder.setForeground(new java.awt.Color(255, 255, 255));
        paidOrder.setText("ÖDƏ");
        paidOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(addOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(editOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(deleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(paidOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paidOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1030, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void masaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masaBtnMousePressed
        setColor(masaBtn);
        resetColor(menuBtn);
        resetColor(orderBtn);
        resetColor(calcBtn);
        MainFrame frame = new MainFrame(dao);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_masaBtnMousePressed

    private void menuBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnMousePressed
        setColor(menuBtn);
        resetColor(masaBtn);
        resetColor(orderBtn);
        resetColor(calcBtn);
        MenuFrame menuFrame = new MenuFrame(dao);
        menuFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBtnMousePressed

    private void orderBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderBtnMousePressed
        setColor(orderBtn);
        resetColor(menuBtn);
        resetColor(masaBtn);
        resetColor(calcBtn);
    }//GEN-LAST:event_orderBtnMousePressed

    private void calcBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcBtnMousePressed
        setColor(calcBtn);
        resetColor(menuBtn);
        resetColor(orderBtn);
        resetColor(masaBtn);
        CalcFrame calcFrame = new CalcFrame(dao);
        calcFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_calcBtnMousePressed

    private void exitBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitBtnMousePressed

    private void loginBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMousePressed
        LoginFrame frame = new LoginFrame(dao);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginBtnMousePressed

    private void addOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderActionPerformed
        AddOrder addOrder = new AddOrder(dao);
        addOrder.setVisible(true);
    }//GEN-LAST:event_addOrderActionPerformed

    private void editOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOrderActionPerformed
        try {
            int rowIndex = orderTable.getSelectedRow();
            Long selectedRow = (Long) orderTable.getValueAt(rowIndex, 0);
            EditOrder editOrder = new EditOrder(dao, selectedRow);
            editOrder.setVisible(true);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Hər hansı bir sətri seçin !!!");
        }

    }//GEN-LAST:event_editOrderActionPerformed

    private void deleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrderActionPerformed
        try {
            int rowIndex = orderTable.getSelectedRow();
            Long selectedRow = (Long) orderTable.getValueAt(rowIndex, 0);
            Sifaris_Masa sifarisMasa = dao.getSifarisMasaById(selectedRow);
            Long sifarisId = sifarisMasa.getSifaris().getId();
            Long masaId = sifarisMasa.getCafeTable().getId();
            boolean isDelete = dao.deleteSifaris(sifarisId);
            int isDeleteMsg = JOptionPane.showConfirmDialog(null, "Eminsen?", "Sətri sil", JOptionPane.YES_NO_OPTION);
            if (isDeleteMsg == JOptionPane.YES_OPTION) {
                boolean isDeleteSifarisMasa = dao.deleteSifarisMasa(selectedRow);
                if (isDeleteSifarisMasa) {
                    JOptionPane.showMessageDialog(null, "Sifariş Silindi...");
                }
            }
            List<Sifaris_Masa> sifarisMasaList = dao.getSifarisMasaList();
            for (Sifaris_Masa sifarisMasa1 : sifarisMasaList) {
                if (Objects.equals(masaId, sifarisMasa1.getCafeTable().getId())) {
                    boolean changeTableStatus = dao.updateTableStatus(masaId);
                } else {
                    boolean changeTableStatus = dao.updateTableStatusForEmpty(masaId);
                }
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Silmək isdədiyiniz sətri seçin...");
        } catch (Exception ex) {
            Logger.getLogger(OrderFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteOrderActionPerformed

    private void paidOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidOrderActionPerformed
        int rowIndex = orderTable.getSelectedRow();
        Long selectedRow = (Long) orderTable.getValueAt(rowIndex, 0);
        PaidFrame paidFrame = new PaidFrame(dao,selectedRow);
        paidFrame.setVisible(true);
    }//GEN-LAST:event_paidOrderActionPerformed

    void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(64, 43, 100));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrder;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel calcBtn;
    private javax.swing.JLabel calcIcon;
    private javax.swing.JLabel calcText;
    private javax.swing.JPanel content;
    private javax.swing.JButton deleteOrder;
    private javax.swing.JButton editOrder;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JLabel loginIcon;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel masaBtn;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuBtn;
    private javax.swing.JLabel menuIcon;
    private javax.swing.JLabel menuText;
    private javax.swing.JPanel orderBtn;
    private javax.swing.JLabel orderIcon;
    private javax.swing.JTable orderTable;
    private javax.swing.JLabel orderText;
    private javax.swing.JButton paidOrder;
    private javax.swing.JPanel seperator;
    private javax.swing.JLabel tableIcon;
    private javax.swing.JLabel tableText;
    // End of variables declaration//GEN-END:variables

    private void ViewSifarisInTable(List<Sifaris_Masa> sifarisMasaList) {
        DefaultTableModel table = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };

        orderTable.setModel(table);
        table.addColumn("Id");
        table.addColumn("№");
        table.addColumn("Rezerv");
        table.addColumn("Masa");
        table.addColumn("Sifariş");
        table.addColumn("Hesab");
        table.addColumn("Sifariş Vaxtı");

        for (Sifaris_Masa sifarisMasa : sifarisMasaList) {
            Object data[] = new Object[]{
                sifarisMasa.getId(), sifarisMasa.getRownum(), sifarisMasa.getSifaris().getResName(),
                sifarisMasa.getCafeTable().getName(), sifarisMasa.getSifaris().getSifaris(), sifarisMasa.getSifaris().getPrice(),
                sifarisMasa.getOrderDate()
            };
            table.addRow(data);
            orderTable.getColumnModel().getColumn(0).setMinWidth(0);
            orderTable.getColumnModel().getColumn(0).setMaxWidth(0);
            orderTable.getColumnModel().getColumn(0).setWidth(0);

        }
    }

}
